name: build

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Gradle Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
      distribution: temurin
      java-version: 8
    - name: NPM CI
      run: npm ci
    - name: Build Game
      run: cd game && ./gradlew setupCIWorkspace && ./gradlew build && cd ..
    - name: Build Installer
      run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Sol-Client-Launcher-Linux
        path: out/make/deb/x64/*.deb
        
  windows:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Gradle Cache
      uses: actions/cache@v2
      with:
        path: |
          %userprofile%\.gradle\caches
          %userprofile%\.gradle\wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**\*.gradle*', '**\gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
      distribution: temurin
      java-version: 8
    - name: NPM CI
      run: npm ci
    - name: Build Game
      run: cd game && .\gradlew setupCIWorkspace && .\gradlew build && cd ..
    - name: Build Installer
      run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Sol-Client-Launcher-Windows
        path: out/make/squirrel.windows/x64/*.exe
        
  macos:
    runs-on: macos-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Gradle Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
      distribution: temurin
      java-version: 8
    - name: NPM CI
      run: npm ci
    - name: Build Game
      run: cd game && ./gradlew setupCIWorkspace && ./gradlew build && cd ..
    - name: Build Installer
      run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Sol-Client-Launcher-MacOS
        path: out/make/*.dmg

  upload:
    if: "startsWith(github.event.head_commit.message, '[create release] ')"

    runs-on: ubuntu-latest
  
    needs: [ linux, windows, macos ]
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v2

    # https://stackoverflow.com/a/61919791
    - name: Retrieve Version
      run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      id: version

    - name: Create a Release
      uses: marvinpinto/action-automatic-releases@latest
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ fromJson(steps.version.outputs.packageJson).version }}
        prerelease: false
        title: ${{ fromJson(steps.version.outputs.packageJson).version }}
        files: |
          Sol-Client-Launcher-Linux/*.deb
          Sol-Client-Launcher-Windows/*.exe
          Sol-Client-Launcher-MacOS/*.dmg
