name: Build Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
    - run: npm ci
    - run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: sol-client-launcher.deb
        path: out/make/deb/x64/*.deb
